### PR TITLE
Add shebang line to ensure we invoke the python interpreter.

### PR DESCRIPTION
**Pull request by achton**

### CODE REVIEW

**Comment by craftyguy** [comment]
Thank you for the contribution!!

I'm wondering if we should be specific and use `#!/usr/bin/env python3` to further emphasize that this was intended to be run in Python3.. (accompanied by a readme update to reflect that this script was developed/tested on 3.6 specifically). Thoughts?

**Comment by achton** [comment]
I considered that, but I have tested this just now with 2.7 (which is the default in e.g. Ubuntu 17) and it works fine. I suspect python3 is not as common as python, as long as major distros do not depned on it (much less include it by default). But as I said: I am very new to Python also, so don't take my word for it :)

In any case, AFAICT this is safe and returns sane output during use. If it turns out there is an *actual* requirement for python3, you could update the shebang line.

**Comment by craftyguy** [comment]
My reason is more political than technical, though there's a technical reasoning too:

Political reasoning: People need to stop using Python2. The future is Python3 (and whatever comes next), and I'd rather not give folks a reason to stick around with 2.x. It's sad that 2.7 is the default in Ubuntu, but rather than derail the conversation further, I'll get off my soap box now 😄 

Technical reasoning: I'm definitely not going to be testing this application on 2.x, so I cannot guarantee that any future changes will be compatible. This project isn't complicated enough to justify the work for setting up something like Travis to cover python 2.x.

**Comment by achton** [comment]
I agree that people should move on. I was in fact poised to uninstall python 2 on my own box, but apt promptly informed me that it would then also uninstall smbclient, Gimp, Atom, compiz and ubuntu-desktop. Packages I am quite fond of, you know :) So for Ubuntu folks at least, I think python2 will be around for a while still.

But anyway, the technical argument is solid. If you do not enforce python3 specifically, then it must be tested on all possible python versions to ensure compatibility (which is unwieldy as you say).

So I have amended the commit as per your suggestion :+1:

**Pull request merged**
